import 'package:intl_phone_field/countries.dart';

import '../../../../../generated/l10n.dart';

List<Country> listOfCountyCodes = [
  Country(
    name: S.current.kazakhstan,
    nameTranslations: {
      'kz': S.current.kazakhstan,
      'en': S.current.kazakhstan,
      'ru': S.current.kazakhstan,
      'uz': S.current.kazakhstan,
      'ky': S.current.kazakhstan,
    },
    flag: "🇰🇿",
    code: "kz",
    dialCode: "7",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.usa,
    nameTranslations: {
      'kz': S.current.usa,
      'en': S.current.usa,
      'ru': S.current.usa,
      'uz': S.current.usa,
      'ky': S.current.usa,
    },
    flag: "🇺🇸",
    code: 'usa',
    dialCode: "1",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.canada,
    nameTranslations: {
      'kz': S.current.canada,
      'en': S.current.canada,
      'uz': S.current.canada,
      'ky': S.current.canada,
      'ru': S.current.canada,
    },
    flag: "🇨🇦",
    code: 'canada',
    dialCode: "1",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.france,
    nameTranslations: {
      'kz': S.current.france,
      'en': S.current.france,
      'uz': S.current.france,
      'ky': S.current.france,
      'ru': S.current.france,
    },
    flag: "🇫🇷",
    code: 'france',
    dialCode: "33",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.uk,
    nameTranslations: {
      'kz': S.current.uk,
      'en': S.current.uk,
      'uz': S.current.uk,
      'ky': S.current.uk,
      'ru': S.current.uk,
    },
    flag: "🇬🇧",
    code: 'uk',
    dialCode: "44",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.germany,
    nameTranslations: {
      'kz': S.current.germany,
      'en': S.current.germany,
      'uz': S.current.germany,
      'ky': S.current.germany,
      'ru': S.current.germany,
    },
    flag: "🇩🇪",
    code: 'germany',
    dialCode: "49",
    minLength: 9,
    maxLength: 13,
  ),
  Country(
    name: S.current.australia,
    nameTranslations: {
      'kz': S.current.australia,
      'en': S.current.australia,
      'uz': S.current.australia,
      'ky': S.current.australia,
      'ru': S.current.australia,
    },
    flag: "🇦🇺",
    code: 'australia',
    dialCode: "61",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.japan,
    nameTranslations: {
      'kz': S.current.japan,
      'en': S.current.japan,
      'uz': S.current.japan,
      'ky': S.current.japan,
      'ru': S.current.japan,
    },
    flag: "🇯🇵",
    code: 'japan',
    dialCode: "81",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.china,
    nameTranslations: {
      'kz': S.current.china,
      'en': S.current.china,
      'uz': S.current.china,
      'ky': S.current.china,
      'ru': S.current.china,
    },
    flag: "🇨🇳",
    code: 'china',
    dialCode: "86",
    minLength: 11,
    maxLength: 12,
  ),
  Country(
    name: S.current.india,
    nameTranslations: {
      'kz': S.current.india,
      'en': S.current.india,
      'uz': S.current.india,
      'ky': S.current.india,
      'ru': S.current.india,
    },
    flag: "🇮🇳",
    code: 'india',
    dialCode: "91",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.uzbekistan,
    nameTranslations: {
      'kz': S.current.uzbekistan,
      'en': S.current.uzbekistan,
      'uz': S.current.uzbekistan,
      'ky': S.current.uzbekistan,
      'ru': S.current.uzbekistan,
    },
    flag: "🇦🇿",
    code: 'uz',
    dialCode: "998",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.russia,
    nameTranslations: {
      'kz': S.current.russia,
      'en': S.current.russia,
      'uz': S.current.russia,
      'ky': S.current.russia,
      'ru': S.current.russia,
    },
    flag: "🇷🇺",
    code: 'ru',
    dialCode: "7",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.belarus,
    nameTranslations: {
      'kz': S.current.belarus,
      'en': S.current.belarus,
      'uz': S.current.belarus,
      'ky': S.current.belarus,
      'ru': S.current.belarus,
    },
    flag: "🇧🇾",
    code: 'belarus',
    dialCode: "375",
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    name: S.current.azerbaijan,
    nameTranslations: {
      'kz': S.current.azerbaijan,
      'en': S.current.azerbaijan,
      'uz': S.current.azerbaijan,
      'ky': S.current.azerbaijan,
      'ru': S.current.azerbaijan,
    },
    flag: "🇦🇿",
    code: 'azerbaijan',
    dialCode: "994",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.armenia,
    nameTranslations: {
      'kz': S.current.armenia,
      'en': S.current.armenia,
      'uz': S.current.armenia,
      'ky': S.current.armenia,
      'ru': S.current.armenia,
    },
    flag: "🇦🇲",
    code: 'armenia',
    dialCode: "374",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.kyrgyzstan,
    nameTranslations: {
      'kz': S.current.kyrgyzstan,
      'en': S.current.kyrgyzstan,
      'ru': S.current.kyrgyzstan,
      'uz': S.current.kyrgyzstan,
      'ky': S.current.kyrgyzstan,
    },
    flag: "🇰🇬",
    code: "kg",
    dialCode: "996",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.moldova,
    nameTranslations: {
      'kz': S.current.moldova,
      'en': S.current.moldova,
      'ru': S.current.moldova,
      'uz': S.current.moldova,
      'ky': S.current.moldova,
    },
    flag: "🇲🇩",
    code: 'moldova',
    dialCode: "373",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.tajikistan,
    nameTranslations: {
      'kz': S.current.tajikistan,
      'en': S.current.tajikistan,
      'ru': S.current.tajikistan,
      'uz': S.current.tajikistan,
      'ky': S.current.tajikistan,
    },
    flag: "🇹🇯",
    code: 'tajikistan',
    dialCode: "992",
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    name: S.current.turkmenistan,
    nameTranslations: {
      'kz': S.current.turkmenistan,
      'en': S.current.turkmenistan,
      'ru': S.current.turkmenistan,
      'uz': S.current.turkmenistan,
      'ky': S.current.turkmenistan,
    },
    flag: "🇹🇲",
    code: 'turkmenistan',
    dialCode: "993",
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    name: S.current.ukraine,
    nameTranslations: {
      'kz': S.current.ukraine,
      'en': S.current.ukraine,
      'ru': S.current.ukraine,
      'uz': S.current.ukraine,
      'ky': S.current.ukraine,
    },
    flag: "🇺🇦",
    code: 'uk',
    dialCode: "380",
    minLength: 9,
    maxLength: 9,
  ),
];
